[package]
name = "optee-utee"
version = "0.1.0"
authors = ["Mingshen Sun <mssun@mesalock-linux.org>"]
edition = "2018"

[dependencies]
optee-utee-sys = { path = "optee-utee-sys" }
optee-utee-macros = { path = "macros" }
libc = { path = "../rust/libc", version = "0.2.49" }
bitflags = "1.0.4"

[workspace]
members = ['systest']
