[dependencies.std]
path = "../rust/rust/src/libstd"

[patch.crates-io]
libc =  { path = "../rust/libc" }
compiler_builtins =  { path = "../rust/compiler-builtins" }
rustc-std-workspace-core = { path = "../rust/rust/src/tools/rustc-std-workspace-core" }
