[package]
name = "systest"
version = "0.1.0"
authors = ["Mingshen Sun <mssun@mesalock-linux.org>"]
edition = "2018"

[dependencies]
optee-utee-sys = { path = "../optee-utee-sys" }
libc = "0.2"

[build-dependencies]
ctest = "0.2"
